### ISSUE TITLE
关于生成解决方案报错的问题

### ISSUE THREAD

**Issue by yongbaoXu** [sunxvming/navmesh#3]
您好，我最近在学习navmesh，看到了您的代码，所以下载后想学习一下
我使用cmake生成sln文件后，用vs2019打开，但是点击生成解决方案时，运行报错，希望能请教一下您
谢谢！
![image](https://github.com/sunxvming/navmesh/assets/28248511/79fa41e0-bc3c-4e4a-9ee1-da1b93681e74)

**Comment by sunxvming** [comment]
应该是用cmake生成工程的时候哪一步出错了吧，你再多尝试一下
